### ISSUE TITLE
CT  api mismatches present

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#167]
```
gravity-force-lab-basics : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: api mismatches present:

gravityForceLabBasics.gravityForceLabBasicsScreen.model.resetInProgressProperty:  3. Any registered PhetioObject must be included in the schema
Error: Assertion failed: api mismatches present:

gravityForceLabBasics.gravityForceLabBasicsScreen.model.resetInProgressProperty:  3. Any registered PhetioObject must be included in the schema
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertOutIfErrorsPresent (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/tandem/js/phetioAPIValidation.js?bust=1562768800161:249:9)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/tandem/js/phetioAPIValidation.js?bust=1562768800161:158:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/phet-io/js/phetioEngine.js?bust=1562768800161:137:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/axon/js/TinyEmitter.js?bust=1562768800161:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/axon/js/Emitter.js?bust=1562768800161:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/axon/js/Action.js?bust=1562768800161:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/axon/js/Emitter.js?bust=1562768800161:71:21)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/joist/js/Sim.js?bust=1562768800161:846:50
id: Bayes Chrome
Approximately 7/10/2019, 7:18:54 AM
gravity-force-lab-basics : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: api mismatches present:

gravityForceLabBasics.gravityForceLabBasicsScreen.model.resetInProgressProperty:  3. Any registered PhetioObject must be included in the schema
Error: Assertion failed: api mismatches present:

gravityForceLabBasics.gravityForceLabBasicsScreen.model.resetInProgressProperty:  3. Any registered PhetioObject must be included in the schema
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/assert/js/assert.js:22:13)
    at PhetioAPIValidation.assertOutIfErrorsPresent (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/tandem/js/phetioAPIValidation.js?bust=1562768800161:249:9)
    at PhetioAPIValidation.onSimStarted (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/tandem/js/phetioAPIValidation.js?bust=1562768800161:158:14)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/phet-io/js/phetioEngine.js?bust=1562768800161:137:29
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/axon/js/TinyEmitter.js?bust=1562768800161:59:55)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/axon/js/Emitter.js?bust=1562768800161:46:31
    at Emitter.execute (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/axon/js/Action.js?bust=1562768800161:177:20)
    at Emitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/axon/js/Emitter.js?bust=1562768800161:71:21)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/joist/js/Sim.js?bust=1562768800161:846:50
id: Bayes Chrome
Approximately 7/10/2019, 7:18:54 AM
gravity-force-lab-basics : phet-io-tests : no-assert
7 out of 9 tests passed. 2 failed.
SimTests: gravity-force-lab-basics: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: api mismatches present:

gravityForceLabBasics.gravityForceLabBasicsScreen.model.resetInProgressProperty:  3. Any registered PhetioObject must be included in the schema
https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/phet-io-wrappers/js/tests/SimTests.js?bust=1562768730097:318

SimTests: gravity-force-lab-basics: event indexing failed:
Uncaught Error: Uncaught Error: Assertion failed: api mismatches present:

gravityForceLabBasics.gravityForceLabBasicsScreen.model.resetInProgressProperty:  3. Any registered PhetioObject must be included in the schema
https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/phet-io-wrappers/js/tests/SimTests.js?bust=1562768730097:514


id: Bayes Chrome
Approximately 7/10/2019, 7:18:54 AM
gravity-force-lab-basics : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: this.play is not a function
TypeError: this.play is not a function
    at CheckboxSoundGenerator.loadCompleteAction (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/tambo/js/sound-generators/MultiClip.js?bust=1562766812495:158:50)
    at AudioContext.<anonymous> (https://bayes.colorado.edu/continuous-testing/snapshot-1562764734772/tambo/js/sound-generators/MultiClip.js?bust=1562766812495:85:45)
id: Bayes Chrome
Approximately 7/10/2019, 7:18:54 AM
```

**Comment by zepumph** [comment]
This was triggered because the phet-io api wasn't updated with changes in #166. Fixed in the above commit and discussed more over in that issue. Thanks @KatieWoe. Closing
