### ISSUE TITLE
CT namespace phetCore already exists

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#195]
@jonathanolson since it may be related to https://github.com/phetsims/gravity-force-lab-basics/issues/194
```
gravity-force-lab-basics : accessibility-fuzz : require.js : load
Query: brand=phet&ea&fuzz&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583496639376:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : accessibility-fuzz : require.js : run
Query: brand=phet&ea&fuzz&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583496639376:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : accessibility-fuzzBoard : require.js : load
Query: brand=phet&ea&fuzzBoard&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583496825819:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : accessibility-fuzzBoard : require.js : run
Query: brand=phet&ea&fuzzBoard&a11y&memoryLimit=1000
Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583496825819:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : build : phet
Failure to grunt snapshot-1583494443367/gravity-force-lab-basics:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (gravity-force-lab-basics, brands: phet)
Building brand: phet
>> Webpack build complete: 6240ms
Fatal error: Perennial task failed:
Error: ENOENT: no such file or directory, open '../snapshot-1583494443367/axon/js/Action.js'
  at Object.openSync (fs.js:443:3)
  at Object.readFileSync (fs.js:343:35)
  at usedModules.map.usedModule (/data/share/phet/continuous-testing/snapshot-1583494443367/chipper/js/grunt/getStringMap.js:42:62)
  at Array.map (<anonymous>:null:null)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1583494443367/chipper/js/grunt/getStringMap.js:42:40)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1583494443367/chipper/js/grunt/buildRunnable.js:112:21)

Full Error details:
{
  "errno": -2,
  "syscall": "open",
  "code": "ENOENT",
  "path": "../snapshot-1583494443367/axon/js/Action.js"
}


Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : build : phet-io
Failure to grunt snapshot-1583494443367-phet-io/gravity-force-lab-basics:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (gravity-force-lab-basics, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 7165ms
Fatal error: Perennial task failed:
Error: ENOENT: no such file or directory, open '../snapshot-1583494443367-phet-io/axon/js/Action.js'
  at Object.openSync (fs.js:443:3)
  at Object.readFileSync (fs.js:343:35)
  at usedModules.map.usedModule (/data/share/phet/continuous-testing/snapshot-1583494443367-phet-io/chipper/js/grunt/getStringMap.js:42:62)
  at Array.map (<anonymous>:null:null)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1583494443367-phet-io/chipper/js/grunt/getStringMap.js:42:40)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1583494443367-phet-io/chipper/js/grunt/buildRunnable.js:112:21)

Full Error details:
{
  "errno": -2,
  "syscall": "open",
  "code": "ENOENT",
  "path": "../snapshot-1583494443367-phet-io/axon/js/Action.js"
}


Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : fuzz : require.js : load
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583496562738:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : fuzz : require.js : run
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583496562738:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : phet-io-fuzz : require.js : load
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583500896108:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : phet-io-fuzz : require.js : run
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583500896108:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : phet-io-mirror-inputs-fuzz : require.js : load
Uncaught Error: Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583497536148:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : phet-io-mirror-inputs-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583497536148:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : phet-io-state-fuzz : require.js : load
Uncaught Error: Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583498934181:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : phet-io-state-fuzz : require.js : load
Uncaught Error: Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583498934190:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : phet-io-state-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583498934181:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : phet-io-state-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583498934190:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : phet-io-studio-fuzz : require.js : load
Uncaught Error: Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583495983743:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : phet-io-studio-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583495983743:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : xss-fuzz : load
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583501976911:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
gravity-force-lab-basics : xss-fuzz : run
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught Error: Assertion failed: namespace phetCore already exists
Error: Assertion failed: namespace phetCore already exists
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583494443367/assert/js/assert.js?bust=1583501976911:22:13)
    at new Namespace (https://bayes.colorado.edu/continuous-testing/phet-core/js/Namespace.js:19:15)
    at https://bayes.colorado.edu/continuous-testing/phet-core/js/phetCore.js:6:18
id: Bayes Chrome
Approximately 3/6/2020, 4:34:03 AM
```

**Comment by jonathanolson** [comment]
Possibly! I just applied some fixes, and I can't reproduce the errors locally now. Let me know if this continues in CT?

**Comment by jessegreenberg** [comment]
This is pretty old and nothing like this is showing up on CT currently.
