### ISSUE TITLE
CT Cannot read property removeInputListener of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#197]
```
gravity-force-lab-basics : phet-io-state-fuzz : require.js : run
Uncaught Error: Cannot read property 'removeInputListener' of null
TypeError: Cannot read property 'removeInputListener' of null
    at ShapeHitDetector.interrupt (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tappi/js/view/ShapeHitDetector.js:220:18)
    at GFLBScreenView.interruptInput (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/scenery/js/nodes/Node.js:1983:38)
    at GFLBScreenView.interruptSubtreeInput (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/scenery/js/nodes/Node.js:1996:10)
    at Rectangle.interruptSubtreeInput (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/scenery/js/nodes/Node.js:2000:21)
    at Node.interruptSubtreeInput (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/scenery/js/nodes/Node.js:2000:21)
    at Display.set interactive [as interactive] (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/scenery/js/display/Display.js:644:22)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/joist/js/Sim.js:556:30
    at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/axon/js/TinyEmitter.js:65:53)
    at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/axon/js/Property.js:276:25)
    at BooleanProperty.set (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/axon/js/Property.js:175:14)
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
gravity-force-lab-basics : phet-io-state-fuzz : require.js : run
Uncaught Error: Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch
Error: Assertion failed: mismatched index, possible start/end mismatch
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/assert/js/assert.js?bust=1583761639555:22:13)
    at DataStream.end (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/dataStream.js:267:15)
    at PhetioCommandProcessor.phetioEndEvent (https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/tandem/js/PhetioObject.js:421:30)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1583745402972/phet-io/js/phetioCommandProcessor.js:107:18
id: Bayes Chrome
Approximately 3/9/2020, 3:16:42 AM
```

**Comment by zepumph** [comment]
@jessegreenberg has been working on this sim, let me know if you need help!

**Comment by jessegreenberg** [comment]
Thanks @KatieWoe, fixed in https://github.com/phetsims/tappi/commit/05a8836ce48f2f101003fd2d89e3a0ade1dc73c0
