### ISSUE TITLE
CT Failure to grunt

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#200]
```
gravity-force-lab-basics : build : phet
Failure to grunt snapshot-1584923625895/gravity-force-lab-basics:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (gravity-force-lab-basics, brands: phet)
Building brand: phet
>> Webpack build complete: 5283ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Missing string information for gravity-force-lab a11y.massControlsLabel
  at locales.forEach.locale (/data/share/phet/continuous-testing/snapshot-1584923625895/chipper/js/grunt/getStringMap.js:140:9)
  at Array.forEach (<anonymous>:null:null)
  at partialStringKeys.forEach.partialStringKey (/data/share/phet/continuous-testing/snapshot-1584923625895/chipper/js/grunt/getStringMap.js:129:15)
  at Array.forEach (<anonymous>:null:null)
  at reposUsed.forEach.repo (/data/share/phet/continuous-testing/snapshot-1584923625895/chipper/js/grunt/getStringMap.js:128:23)
  at Array.forEach (<anonymous>:null:null)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1584923625895/chipper/js/grunt/getStringMap.js:104:13)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1584923625895/chipper/js/grunt/buildRunnable.js:112:21)
  at process._tickCallback (internal/process/next_tick.js:68:7)

Full Error details:
{
  "generatedMessage": false,
  "name": "AssertionError [ERR_ASSERTION]",
  "code": "ERR_ASSERTION",
  "actual": false,
  "expected": true,
  "operator": "=="
}


Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : build : phet-io
Failure to grunt snapshot-1584923625895-phet-io/gravity-force-lab-basics:
Running "lint-all" task

Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (gravity-force-lab-basics, brands: phet, phet-io)
Building brand: phet
>> Webpack build complete: 5537ms
Fatal error: Perennial task failed:
AssertionError [ERR_ASSERTION]: Missing string information for gravity-force-lab a11y.massControlsLabel
  at locales.forEach.locale (/data/share/phet/continuous-testing/snapshot-1584923625895-phet-io/chipper/js/grunt/getStringMap.js:140:9)
  at Array.forEach (<anonymous>:null:null)
  at partialStringKeys.forEach.partialStringKey (/data/share/phet/continuous-testing/snapshot-1584923625895-phet-io/chipper/js/grunt/getStringMap.js:129:15)
  at Array.forEach (<anonymous>:null:null)
  at reposUsed.forEach.repo (/data/share/phet/continuous-testing/snapshot-1584923625895-phet-io/chipper/js/grunt/getStringMap.js:128:23)
  at Array.forEach (<anonymous>:null:null)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1584923625895-phet-io/chipper/js/grunt/getStringMap.js:104:13)
  at module.exports (/data/share/phet/continuous-testing/snapshot-1584923625895-phet-io/chipper/js/grunt/buildRunnable.js:112:21)
  at process._tickCallback (internal/process/next_tick.js:68:7)

Full Error details:
{
  "generatedMessage": false,
  "name": "AssertionError [ERR_ASSERTION]",
  "code": "ERR_ASSERTION",
  "actual": false,
  "expected": true,
  "operator": "=="
}


Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/gravity-force-lab-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/gravity-force-lab-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : interactive-description-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/gravity-force-lab-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : interactive-description-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/gravity-force-lab-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : interactive-description-fuzzBoard : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/gravity-force-lab-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : interactive-description-fuzzBoard : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/gravity-force-lab-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzzBoard&supportsDescriptions&memoryLimit=1000
Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : phet-io-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/gravity-force-lab-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : phet-io-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/gravity-force-lab-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : phet-io-mirror-inputs-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io-wrappers/mirror-inputs/?sim=gravity-force-lab-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : phet-io-mirror-inputs-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io-wrappers/mirror-inputs/?sim=gravity-force-lab-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : phet-io-state-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io-wrappers/state/?sim=gravity-force-lab-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : phet-io-state-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/phet-io-wrappers/state/?sim=gravity-force-lab-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : phet-io-studio-fuzz : require.js : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/studio/?sim=gravity-force-lab-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : phet-io-studio-fuzz : require.js : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/studio/?sim=gravity-force-lab-basics&phetioDebug&fuzz&postMessageToParent&postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload
Uncaught Error: Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : xss-fuzz : load
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/gravity-force-lab-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
gravity-force-lab-basics : xss-fuzz : run
https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/gravity-force-lab-basics_en.html?postMessageOnLoad&postMessageOnError&postMessageOnBeforeUnload&brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Query: brand=phet&ea&fuzz&stringTest=xss&memoryLimit=1000
Uncaught TypeError: Cannot read property 'massControlsLabel' of undefined
TypeError: Cannot read property 'massControlsLabel' of undefined
    at https://bayes.colorado.edu/continuous-testing/snapshot-1584923625895/gravity-force-lab-basics/js/view/GFLBScreenView.js:62:61
id: Bayes Chrome
Approximately 3/22/2020, 6:33:45 PM
```

**Comment by zepumph** [comment]
I forgot to push a commit last night, it should be fixed now.

**Comment by zepumph** [comment]
CT is clear. closing
