### ISSUE TITLE
CT unrecognized force value, smaller than expected

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#201]
```
gravity-force-lab-basics : fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab-basics/gravity-force-lab-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589868430291%22%2C%22timestamp%22%3A1589871684558%7D&brand=phet&ea&fuzz&memoryLimit=1000
Query: brand=phet&ea&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: unrecognized force value, smaller than expected: 0.667408
Error: Assertion failed: unrecognized force value, smaller than expected: 0.667408
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/assert/js/assert.js:22:13)
at GFLBForceDescriber.getForceVectorIndex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab-basics/js/view/describers/GFLBForceDescriber.js:53:15)
at GFLBForceDescriber.getVectorSize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:374:31)
at GFLBForceDescriber.getForceVectorsSummaryText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:195:28)
at GravityForceLabScreenSummaryNode.updateForceVectorSummary (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:146:69)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:114:12
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Multilink.js:38:18)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:270:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:170:14)
id: Bayes Chrome
Snapshot from 5/19/2020, 12:07:10 AM

----------------------------------

gravity-force-lab-basics : interactive-description-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab-basics/gravity-force-lab-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22interactive-description-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589868430291%22%2C%22timestamp%22%3A1589888334964%7D&brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Query: brand=phet&ea&fuzz&supportsDescriptions&memoryLimit=1000
Uncaught Error: Assertion failed: unrecognized force value, smaller than expected: 0.6809590858075707
Error: Assertion failed: unrecognized force value, smaller than expected: 0.6809590858075707
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/assert/js/assert.js:22:13)
at GFLBForceDescriber.getForceVectorIndex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab-basics/js/view/describers/GFLBForceDescriber.js:53:15)
at GFLBForceDescriber.getVectorSize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:374:31)
at GFLBForceDescriber.getForceVectorsSummaryText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:195:28)
at GravityForceLabScreenSummaryNode.updateForceVectorSummary (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:146:69)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:114:12
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Multilink.js:38:18)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:270:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:170:14)
id: Bayes Chrome
Snapshot from 5/19/2020, 12:07:10 AM

----------------------------------

gravity-force-lab-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab-basics/gravity-force-lab-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589868430291%22%2C%22timestamp%22%3A1589871338093%7D&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: unrecognized force value, smaller than expected: 0.6809590858075707
Error: Assertion failed: unrecognized force value, smaller than expected: 0.6809590858075707
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/assert/js/assert.js:22:13)
at GFLBForceDescriber.getForceVectorIndex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab-basics/js/view/describers/GFLBForceDescriber.js:53:15)
at GFLBForceDescriber.getVectorSize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:374:31)
at GFLBForceDescriber.getForceVectorsSummaryText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:195:28)
at GravityForceLabScreenSummaryNode.updateForceVectorSummary (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:146:69)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:114:12
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Multilink.js:38:18)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:270:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:170:14)
id: Bayes Chrome
Snapshot from 5/19/2020, 12:07:10 AM

----------------------------------

gravity-force-lab-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab-basics/gravity-force-lab-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589868430291%22%2C%22timestamp%22%3A1589890175795%7D&brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Query: brand=phet-io&phetioStandalone&ea&phetioValidateTandems&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: unrecognized force value, smaller than expected: 0.667408
Error: Assertion failed: unrecognized force value, smaller than expected: 0.667408
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/assert/js/assert.js:22:13)
at GFLBForceDescriber.getForceVectorIndex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab-basics/js/view/describers/GFLBForceDescriber.js:53:15)
at GFLBForceDescriber.getVectorSize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:374:31)
at GFLBForceDescriber.getForceVectorsSummaryText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:195:28)
at GravityForceLabScreenSummaryNode.updateForceVectorSummary (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:146:69)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:114:12
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Multilink.js:38:18)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:270:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:170:14)
id: Bayes Chrome
Snapshot from 5/19/2020, 12:07:10 AM

----------------------------------

gravity-force-lab-basics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/phet-io-wrappers/state/?sim=gravity-force-lab-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589868430291%22%2C%22timestamp%22%3A1589876723229%7D
Uncaught Error: Uncaught Error: Assertion failed: unrecognized force value, smaller than expected: 0.667408
Error: Assertion failed: unrecognized force value, smaller than expected: 0.667408
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/assert/js/assert.js:22:13)
at GFLBForceDescriber.getForceVectorIndex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab-basics/js/view/describers/GFLBForceDescriber.js:53:15)
at GFLBForceDescriber.getVectorSize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:374:31)
at GFLBForceDescriber.getForceVectorsSummaryText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:195:28)
at GravityForceLabScreenSummaryNode.updateForceVectorSummary (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:146:69)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:114:12
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Multilink.js:38:18)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:270:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:170:14)
id: Bayes Chrome
Snapshot from 5/19/2020, 12:07:10 AM

----------------------------------

gravity-force-lab-basics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/phet-io-wrappers/state/?sim=gravity-force-lab-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589868430291%22%2C%22timestamp%22%3A1589889954973%7D
Uncaught Error: Uncaught Error: Assertion failed: unrecognized force value, smaller than expected: 0.6949271137026239
Error: Assertion failed: unrecognized force value, smaller than expected: 0.6949271137026239
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/assert/js/assert.js:22:13)
at GFLBForceDescriber.getForceVectorIndex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab-basics/js/view/describers/GFLBForceDescriber.js:53:15)
at GFLBForceDescriber.getVectorSize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:374:31)
at GFLBForceDescriber.getForceVectorsSummaryText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:195:28)
at GravityForceLabScreenSummaryNode.updateForceVectorSummary (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:146:69)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:114:12
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Multilink.js:38:18)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:270:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:170:14)
id: Bayes Chrome
Snapshot from 5/19/2020, 12:07:10 AM

----------------------------------

gravity-force-lab-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/studio/?sim=gravity-force-lab-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1589868430291%22%2C%22timestamp%22%3A1589888079923%7D
Uncaught Error: Uncaught Error: Assertion failed: unrecognized force value, smaller than expected: 0.667408
Error: Assertion failed: unrecognized force value, smaller than expected: 0.667408
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/assert/js/assert.js:22:13)
at GFLBForceDescriber.getForceVectorIndex (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab-basics/js/view/describers/GFLBForceDescriber.js:53:15)
at GFLBForceDescriber.getVectorSize (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:374:31)
at GFLBForceDescriber.getForceVectorsSummaryText (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/inverse-square-law-common/js/view/describers/ForceDescriber.js:195:28)
at GravityForceLabScreenSummaryNode.updateForceVectorSummary (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:146:69)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/gravity-force-lab/js/view/GravityForceLabScreenSummaryNode.js:114:12
at listener (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Multilink.js:38:18)
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/TinyEmitter.js:69:53)
at DerivedProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:270:25)
at DerivedProperty.set (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1589868430291/axon/js/Property.js:170:14)
id: Bayes Chrome
Snapshot from 5/19/2020, 12:07:10 AM
```

**Comment by jessegreenberg** [comment]
This has not shown on CT for a very long time and this issue is pretty old. I am guessing this is no longer an issue, closing.
