### ISSUE TITLE
CT converting circular structure to JSON

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#248]
```
gravity-force-lab-basics : build
Build failed with status code 3:
Running "report-media" task

Running "clean" task

Running "build" task
Building runnable repository (gravity-force-lab-basics, brands: phet, phet-io)
Building brand: phet
Fatal error: Converting circular structure to JSON

Webpack build errors: [ ModuleNotFoundError: Module not found: Error: Can't resolve '../../../../tappi/js/VibrationManageriOS.js' in '/data/share/phet/continuous-testing/ct-snapshots/1603943177449/gravity-force-lab-basics/js/view'
at factory.create (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:925:10)
at factory (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/NormalModuleFactory.js:401:22)
at resolver (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/NormalModuleFactory.js:130:21)
at asyncLib.parallel (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/NormalModuleFactory.js:224:22)
at /data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/neo-async/async.js:2830:7
at /data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/neo-async/async.js:6877:13
at normalResolver.resolve (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/NormalModuleFactory.js:214:25)
at doResolve (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:213:14)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:15:1)
at resolver.doResolve (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:15:1)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:27:1)
at resolver.doResolve (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn42 (<anonymous>:16:1)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn1 (<anonymous>:16:1)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn1 (<anonymous>:16:1)
at hook.callAsync (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/Resolver.js:285:5)
at _fn0 (<anonymous>:15:1)
at fs.stat (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/DirectoryExistsPlugin.js:27:15)
at process.nextTick (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:85:15)
at process._tickCallback (internal/process/next_tick.js:61:11)

resolve '../../../../tappi/js/VibrationManageriOS.js' in '/data/share/phet/continuous-testing/ct-snapshots/1603943177449/gravity-force-lab-basics/js/view'
using description file: /data/share/phet/continuous-testing/ct-snapshots/1603943177449/gravity-force-lab-basics/package.json (relative path: ./js/view)
Field 'browser' doesn't contain a valid alias configuration
No description file found
no extension
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/tappi/js/VibrationManageriOS.js doesn't exist
.wasm
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/tappi/js/VibrationManageriOS.js.wasm doesn't exist
.mjs
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/tappi/js/VibrationManageriOS.js.mjs doesn't exist
.js
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/tappi/js/VibrationManageriOS.js.js doesn't exist
.json
Field 'browser' doesn't contain a valid alias configuration
/data/share/phet/continuous-testing/ct-snapshots/tappi/js/VibrationManageriOS.js.json doesn't exist
as directory
/data/share/phet/continuous-testing/ct-snapshots/tappi/js/VibrationManageriOS.js doesn't exist,
ChunkRenderError: /data/share/phet/continuous-testing/ct-snapshots/1603943177449/gravity-force-lab-basics/js/gravity-force-lab-basics-main.js b7ea01f7c4239305578411b65139cb12
Unexpected token (491:35)
|
| // sends messages to the containing Swift app
| const vibrationManager = new !(function webpackMissingModule() { var e = new Error("Cannot find module '../../../../tappi/js/VibrationManageriOS.js'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())();
|
| // collection of input and simulation events that will be recorded during user interaction
at Compilation.createChunkAssets (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:2202:6)
at hooks.optimizeTree.callAsync.err (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1397:10)
at AsyncSeriesHook.eval [as callAsync] (<anonymous>:6:1)
at AsyncSeriesHook.lazyCompileHook (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/tapable/lib/Hook.js:154:20)
at Compilation.seal (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1342:27)
at compilation.finish.err (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compiler.js:675:18)
at hooks.finishModules.callAsync.err (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1261:4)
at AsyncSeriesHook.eval [as callAsync] (<anonymous>:24:1)
at AsyncSeriesHook.lazyCompileHook (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/tapable/lib/Hook.js:154:20)
at Compilation.finish (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1253:28)
at hooks.make.callAsync.err (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compiler.js:672:17)
at _err0 (<anonymous>:11:1)
at _addModuleChain (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1185:12)
at processModuleDependencies.err (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1097:9)
at process._tickCallback (internal/process/next_tick.js:61:11)

SyntaxError: /data/share/phet/continuous-testing/ct-snapshots/1603943177449/gravity-force-lab-basics/js/gravity-force-lab-basics-main.js b7ea01f7c4239305578411b65139cb12
Unexpected token (491:35)
|
| // sends messages to the containing Swift app
| const vibrationManager = new !(function webpackMissingModule() { var e = new Error("Cannot find module '../../../../tappi/js/VibrationManageriOS.js'"); e.code = 'MODULE_NOT_FOUND'; throw e; }())();
|
| // collection of input and simulation events that will be recorded during user interaction
at Parser.pp$4.raise (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:2825:15)
at Parser.pp.unexpected (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:689:10)
at Parser.pp$3.parseExprAtom (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:2270:12)
at Parser.pp$3.parseNew (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:2391:45)
at Parser.pp$3.parseExprAtom (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:2257:19)
at Parser.pp$3.parseExprSubscripts (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:2089:21)
at Parser.pp$3.parseMaybeUnary (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:2066:19)
at Parser.pp$3.parseExprOps (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:2010:21)
at Parser.pp$3.parseMaybeConditional (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:1993:21)
at Parser.pp$3.parseMaybeAssign (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:1968:21)
at Parser.pp$1.parseVar (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:1228:26)
at Parser.pp$1.parseVarStatement (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:1092:10)
at Parser.pp$1.parseStatement (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:842:19)
at Parser.pp$1.parseBlock (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:1161:23)
at Parser.pp$1.parseStatement (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:845:36)
at Parser.pp$1.parseIfStatement (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:990:28)
at Parser.pp$1.parseStatement (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:834:33)
at Parser.pp$1.parseBlock (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:1161:23)
at Parser.pp$3.parseFunctionBody (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:2671:24)
at Parser.pp$3.parseMethod (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:2612:10)
at Parser.pp$1.parseClassMethod (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:1387:25)
at Parser.pp$1.parseClassElement (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:1376:10)
at Parser.pp$1.parseClass (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:1315:26)
at Parser.pp$1.parseStatement (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:833:19)
at Parser.pp$1.parseTopLevel (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:746:23)
at Parser.parse (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:553:17)
at Function.parse (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/node_modules/acorn/dist/acorn.js:576:37)
at Function.parse (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Parser.js:2409:22)
at ConcatenatedModule.source (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/optimize/ConcatenatedModule.js:716:19)
at ModuleTemplate.render (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/ModuleTemplate.js:54:32)
at modules.map.module (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Template.js:233:28)
at Array.map (<anonymous>:null:null)
at Function.renderChunkModules (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Template.js:230:30)
at compilation.mainTemplate.hooks.modules.tap (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/JavascriptModulesPlugin.js:86:23)
at SyncWaterfallHook.eval (<anonymous>:7:16)
at SyncWaterfallHook.lazyCompileHook (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/tapable/lib/Hook.js:154:20)
at MainTemplate.hooks.render.tap (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/MainTemplate.js:162:25)
at SyncWaterfallHook.eval (<anonymous>:7:16)
at SyncWaterfallHook.lazyCompileHook (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/tapable/lib/Hook.js:154:20)
at MainTemplate.render (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/MainTemplate.js:438:34)
at Object.render (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/JavascriptModulesPlugin.js:65:34)
at Compilation.createChunkAssets (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:2172:29)
at hooks.optimizeTree.callAsync.err (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1397:10)
at AsyncSeriesHook.eval [as callAsync] (<anonymous>:6:1)
at AsyncSeriesHook.lazyCompileHook (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/tapable/lib/Hook.js:154:20)
at Compilation.seal (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1342:27)
at compilation.finish.err (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compiler.js:675:18)
at hooks.finishModules.callAsync.err (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1261:4)
at AsyncSeriesHook.eval [as callAsync] (<anonymous>:24:1)
at AsyncSeriesHook.lazyCompileHook (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/tapable/lib/Hook.js:154:20)
at Compilation.finish (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1253:28)
at hooks.make.callAsync.err (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compiler.js:672:17)
at _err0 (<anonymous>:11:1)
at _addModuleChain (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1185:12)
at processModuleDependencies.err (/data/share/phet/continuous-testing/ct-snapshots/1603943177449/chipper/node_modules/webpack/lib/Compilation.js:1097:9)
at process._tickCallback (internal/process/next_tick.js:61:11)
]
Snapshot from 10/28/2020, 9:46:17 PM

----------------------------------

gravity-force-lab-basics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603943177449/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gravity-force-lab-basics&phetioDebug
1 out of 1 tests passed. 0 failed.

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 10/28/2020, 9:46:17 PM

----------------------------------

gravity-force-lab-basics : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1603943177449/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gravity-force-lab-basics
1 out of 1 tests passed. 0 failed.

Did not complete in 200000ms, may not have completed all tests
id: Bayes Chrome
Snapshot from 10/28/2020, 9:46:17 PM
```

**Comment by jessegreenberg** [comment]
Sorry about that, path fixed in above commit and sim is building again.
