### ISSUE TITLE
CT cannot read property copy of null

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#262]
```
gravity-force-lab-basics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/phet-io-wrappers/state/?sim=gravity-force-lab-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608697201899%22%2C%22timestamp%22%3A1608699841342%7D
Uncaught Error: Cannot read property 'copy' of null
TypeError: Cannot read property 'copy' of null
at GFLBScreenView.globalToLocalPoint (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/nodes/Node.js:5210:31)
at ShapeHitDetector.exit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/tappi/js/view/ShapeHitDetector.js:162:39)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1833:25)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1794:10)
at Input.exitEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1761:14)
at Input.removeTemporaryPointers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:882:14)
at Display.set interactive [as interactive] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/display/Display.js:773:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/joist/js/Sim.js:600:32
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 12/22/2020, 9:20:01 PM

----------------------------------

gravity-force-lab-basics : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/phet-io-wrappers/state/?sim=gravity-force-lab-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1608697201899%22%2C%22timestamp%22%3A1608716083642%7D
Uncaught Error: Cannot read property 'copy' of null
TypeError: Cannot read property 'copy' of null
at GFLBScreenView.globalToLocalPoint (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/nodes/Node.js:5210:31)
at ShapeHitDetector.exit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/tappi/js/view/ShapeHitDetector.js:162:39)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1833:25)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1794:10)
at Input.exitEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1761:14)
at Input.removeTemporaryPointers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:882:14)
at Display.set interactive [as interactive] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/display/Display.js:773:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/joist/js/Sim.js:600:32
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/axon/js/Property.js:280:25)
id: Bayes Chrome
Snapshot from 12/22/2020, 9:20:01 PM

----------------------------------

gravity-force-lab-basics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gravity-force-lab-basics&phetioDebug
8 out of 9 tests passed. 1 failed.
SimTests: gravity-force-lab-basics: iframe api failed:
Uncaught Error: Cannot read property 'copy' of null
TypeError: Cannot read property 'copy' of null
at GFLBScreenView.globalToLocalPoint (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/nodes/Node.js:5210:31)
at ShapeHitDetector.exit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/tappi/js/view/ShapeHitDetector.js:162:39)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1833:25)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1794:10)
at Input.exitEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1761:14)
at Input.removeTemporaryPointers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:882:14)
at Display.set interactive [as interactive] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/display/Display.js:773:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/joist/js/Sim.js:600:32
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/axon/js/Property.js:280:25)

SimTests: gravity-force-lab-basics: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/assert/js/assert.js:25:13)
at DataStream.end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/phet-io/js/dataStream.js:281:15)
at PhetioCommandProcessor.phetioEndEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/tandem/js/PhetioObject.js:407:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/phet-io/js/phetioCommandProcessor.js:121:18

id: Bayes Chrome
Snapshot from 12/22/2020, 9:20:01 PM

----------------------------------

gravity-force-lab-basics : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gravity-force-lab-basics
8 out of 9 tests passed. 1 failed.
SimTests: gravity-force-lab-basics: iframe api failed:
Uncaught Error: Cannot read property 'copy' of null
TypeError: Cannot read property 'copy' of null
at GFLBScreenView.globalToLocalPoint (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/nodes/Node.js:5210:31)
at ShapeHitDetector.exit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/tappi/js/view/ShapeHitDetector.js:162:39)
at Input.dispatchToListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1833:25)
at Input.dispatchEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1794:10)
at Input.exitEvents (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:1761:14)
at Input.removeTemporaryPointers (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/input/Input.js:882:14)
at Display.set interactive [as interactive] (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/scenery/js/display/Display.js:773:19)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/joist/js/Sim.js:600:32
at TinyEmitter.emit (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/axon/js/TinyEmitter.js:71:18)
at BooleanProperty._notifyListeners (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/axon/js/Property.js:280:25)

SimTests: gravity-force-lab-basics: iframe api failed:
Uncaught Error: Uncaught Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
Error: Assertion failed: mismatched index, possible start/end mismatch. Likely this is downstream of another error, try pausing on caught exceptions.
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/assert/js/assert.js:25:13)
at DataStream.end (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/phet-io/js/dataStream.js:281:15)
at PhetioCommandProcessor.phetioEndEvent (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/tandem/js/PhetioObject.js:407:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1608697201899/phet-io/js/phetioCommandProcessor.js:121:18

id: Bayes Chrome
Snapshot from 12/22/2020, 9:20:01 PM
```

**Comment by zepumph** [comment]
I just assume that this is from self voicing work, please reassign if not.

**Comment by jessegreenberg** [comment]
Error was related to ShapeHitDetector which is no longer used so I removed it. Closing.
