### ISSUE TITLE
CT required tandems must be supplied

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/gravity-force-lab-basics#286]
```
gravity-force-lab-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/gravity-force-lab-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625530209109%22%2C%22timestamp%22%3A1625531326676%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)
id: Bayes Chrome
Snapshot from 7/5/2021, 6:10:09 PM

----------------------------------

gravity-force-lab-basics : phet-io-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/gravity-force-lab-basics_en.html?continuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625530209109%22%2C%22timestamp%22%3A1625560539345%7D&ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Query: ea&brand=phet-io&phetioStandalone&fuzz&memoryLimit=1000
Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)
id: Bayes Chrome
Snapshot from 7/5/2021, 6:10:09 PM

----------------------------------

gravity-force-lab-basics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/phet-io-wrappers/mirror-inputs/?sim=gravity-force-lab-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625530209109%22%2C%22timestamp%22%3A1625533489858%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)
id: Bayes Chrome
Snapshot from 7/5/2021, 6:10:09 PM

----------------------------------

gravity-force-lab-basics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/phet-io-wrappers/mirror-inputs/?sim=gravity-force-lab-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625530209109%22%2C%22timestamp%22%3A1625544736056%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)
id: Bayes Chrome
Snapshot from 7/5/2021, 6:10:09 PM

----------------------------------

gravity-force-lab-basics : phet-io-mirror-inputs-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/phet-io-wrappers/mirror-inputs/?sim=gravity-force-lab-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-mirror-inputs-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625530209109%22%2C%22timestamp%22%3A1625560936030%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)
id: Bayes Chrome
Snapshot from 7/5/2021, 6:10:09 PM

----------------------------------

gravity-force-lab-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/studio/?sim=gravity-force-lab-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625530209109%22%2C%22timestamp%22%3A1625531404195%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)
id: Bayes Chrome
Snapshot from 7/5/2021, 6:10:09 PM

----------------------------------

gravity-force-lab-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/studio/?sim=gravity-force-lab-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625530209109%22%2C%22timestamp%22%3A1625544738845%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)
id: Bayes Chrome
Snapshot from 7/5/2021, 6:10:09 PM

----------------------------------

gravity-force-lab-basics : phet-io-studio-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/studio/?sim=gravity-force-lab-basics&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22gravity-force-lab-basics%22%2C%22phet-io-studio-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1625530209109%22%2C%22timestamp%22%3A1625575769774%7D
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)
id: Bayes Chrome
Snapshot from 7/5/2021, 6:10:09 PM

----------------------------------

gravity-force-lab-basics : phet-io-wrappers-tests : assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gravity-force-lab-basics&phetioDebug
3 out of 4 tests passed. 1 failed.
SimTests: gravity-force-lab-basics: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)
id: Bayes Chrome
Snapshot from 7/5/2021, 6:10:09 PM

----------------------------------

gravity-force-lab-basics : phet-io-wrappers-tests : no-assert
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/phet-io-wrappers/phet-io-wrappers-tests.html?sim=gravity-force-lab-basics
3 out of 4 tests passed. 1 failed.
SimTests: gravity-force-lab-basics: iframe API failed:
Uncaught Error: Uncaught Error: Assertion failed: required tandems must be supplied
Error: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)

Uncaught Error: Uncaught Error: Assertion failed: required tandems must be suppliedError: Assertion failed: required tandems must be supplied
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/assert/js/assert.js:25:13)
at Action.initializePhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:152:17)
at new PhetioObject (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/tandem/js/PhetioObject.js:120:12)
at new Action (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/axon/js/Action.js:93:5)
at new Checkbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/sun/js/Checkbox.js:79:26)
at new GFLBCheckbox (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:93:5)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:57:24
at Array.forEach (<anonymous>)
at new GFLBCheckboxPanel (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBCheckboxPanel.js:52:19)
at new GFLBScreenView (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1625530209109/gravity-force-lab-basics/js/view/GFLBScreenView.js:314:35)
id: Bayes Chrome
Snapshot from 7/5/2021, 6:10:09 PM
```

**Comment by jessegreenberg** [comment]
This was fixed in the above commit.
